"""tournament entries

Revision ID: 8faa70df2891
Revises: c8ecc5a5f104
Create Date: 2026-08-21 16:57:37.984304
"""
from alembic import op
import sqlalchemy as sa


revision = '8faa70df2891'
down_revision = 'c8ecc5a5f104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_slug', sa.String(length=128), nullable=False),
    sa.Column('seed', sa.String(length=32), nullable=False),
    sa.Column('replaced_team_id', sa.Integer(), nullable=True),
    sa.Column('squad_ovr', sa.Integer(), nullable=False),
    sa.Column('squad_json', sa.JSON(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=False),
    sa.Column('coins_awarded', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('run_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['replaced_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_entries_tournament_slug'), ['tournament_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_entries_tournament_slug'))

    op.drop_table('tournament_entries')
    # ### end Alembic commands ###
