"""payments, quests, referrals

Revision ID: 92164fd6196d
Revises: ce3311ea07f9
Create Date: 2026-08-21 18:33:14.827564
"""
from alembic import op
import sqlalchemy as sa


revision = '92164fd6196d'
down_revision = 'ce3311ea07f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('delivered_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('quest_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quest_key', sa.String(length=64), nullable=False),
    sa.Column('times_claimed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coins_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_key', name='uq_quest_user_key')
    )
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_progress_quest_key'), ['quest_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_progress_user_id'), ['user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('inviter_reward', sa.Integer(), nullable=False),
    sa.Column('invitee_reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id', name='uq_referral_invitee')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_inviter_id'), ['inviter_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_inviter_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_quest_progress_quest_key'))

    op.drop_table('quest_progress')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))

    op.drop_table('payments')
    # ### end Alembic commands ###
