"""card ratings and local photos

Revision ID: c8ecc5a5f104
Revises: fd95d2bf8dcb
Create Date: 2026-08-21 15:48:14.432794
"""
from alembic import op
import sqlalchemy as sa


revision = 'c8ecc5a5f104'
down_revision = 'fd95d2bf8dcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ovr', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atk', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('def', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('dig', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('phy', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('clt', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('exp', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('wins', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('draws', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('losses', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('goals_for', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('goals_against', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('best_round', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_players_ovr'), ['ovr'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_rank'), ['rank'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('ovr', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atk', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('def', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('dig', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('phy', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('clt', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('exp', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('wins', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('draws', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('losses', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('goals_for', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('goals_against', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('best_round', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_teams_ovr'), ['ovr'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_rank'), ['rank'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_rank'))
        batch_op.drop_index(batch_op.f('ix_teams_ovr'))
        batch_op.drop_column('best_round')
        batch_op.drop_column('goals_against')
        batch_op.drop_column('goals_for')
        batch_op.drop_column('losses')
        batch_op.drop_column('draws')
        batch_op.drop_column('wins')
        batch_op.drop_column('matches_played')
        batch_op.drop_column('exp')
        batch_op.drop_column('clt')
        batch_op.drop_column('phy')
        batch_op.drop_column('dig')
        batch_op.drop_column('def')
        batch_op.drop_column('atk')
        batch_op.drop_column('rank')
        batch_op.drop_column('ovr')
        batch_op.drop_column('color')
        batch_op.drop_column('photo_path')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_rank'))
        batch_op.drop_index(batch_op.f('ix_players_ovr'))
        batch_op.drop_column('best_round')
        batch_op.drop_column('goals_against')
        batch_op.drop_column('goals_for')
        batch_op.drop_column('losses')
        batch_op.drop_column('draws')
        batch_op.drop_column('wins')
        batch_op.drop_column('matches_played')
        batch_op.drop_column('exp')
        batch_op.drop_column('clt')
        batch_op.drop_column('phy')
        batch_op.drop_column('dig')
        batch_op.drop_column('def')
        batch_op.drop_column('atk')
        batch_op.drop_column('rank')
        batch_op.drop_column('ovr')

    # ### end Alembic commands ###
