"""card durability and permanent cards

Revision ID: ce3311ea07f9
Revises: 8faa70df2891
Create Date: 2026-08-21 17:39:24.191221
"""
from alembic import op
import sqlalchemy as sa


revision = 'ce3311ea07f9'
down_revision = '8faa70df2891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grants_permanent', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('guarantees_goalkeeper', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retired_json', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_permanent', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('tournaments_used', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.drop_column('tournaments_used')
        batch_op.drop_column('is_permanent')

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_column('retired_json')

    with op.batch_alter_table('packs', schema=None) as batch_op:
        batch_op.drop_column('guarantees_goalkeeper')
        batch_op.drop_column('grants_permanent')

    # ### end Alembic commands ###
