"""initial schema

Revision ID: fd95d2bf8dcb
Revises: 
Create Date: 2026-08-21 14:28:43.550490
"""
from alembic import op
import sqlalchemy as sa


revision = 'fd95d2bf8dcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contents_json', sa.JSON(), nullable=False),
    sa.Column('odds_json', sa.JSON(), nullable=True),
    sa.Column('team_card_chance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('teams_synced', sa.Integer(), nullable=False),
    sa.Column('players_synced', sa.Integer(), nullable=False),
    sa.Column('matches_synced', sa.Integer(), nullable=False),
    sa.Column('templates_created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_title', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('tournament_slug', sa.String(length=128), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('round_label', sa.String(length=128), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'COMPLETED', 'CANCELLED', name='match_status', native_enum=False, length=32), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_digital', sa.Integer(), nullable=False),
    sa.Column('away_digital', sa.Integer(), nullable=False),
    sa.Column('home_physical', sa.Integer(), nullable=False),
    sa.Column('away_physical', sa.Integer(), nullable=False),
    sa.Column('home_shootouts', sa.Integer(), nullable=False),
    sa.Column('away_shootouts', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('home_lineup_json', sa.JSON(), nullable=True),
    sa.Column('away_lineup_json', sa.JSON(), nullable=True),
    sa.Column('lineups_source', sa.String(length=16), nullable=True),
    sa.Column('points_calculated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_matches_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_matches_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_tournament_slug'), ['tournament_slug'], unique=False)

    op.create_table('pack_openings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('cards_received', sa.JSON(), nullable=False),
    sa.Column('coins_spent', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pack_openings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pack_openings_user_id'), ['user_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('position', sa.Enum('GOALKEEPER', 'FIELD', name='position', native_enum=False, length=32), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('team_card_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarity', native_enum=False, length=32), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rarity', name='uq_team_rarity')
    )
    with op.batch_alter_table('team_card_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_card_templates_rarity'), ['rarity'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_card_templates_team_id'), ['team_id'], unique=False)

    op.create_table('trade_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'COUNTERED', name='trade_status', native_enum=False, length=32), nullable=False),
    sa.Column('sender_cards', sa.JSON(), nullable=False),
    sa.Column('receiver_cards', sa.JSON(), nullable=False),
    sa.Column('sender_coins', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('counter_of_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counter_of_id'], ['trade_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_offers_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_offers_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_offers_status'), ['status'], unique=False)

    op.create_table('user_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_template_id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Enum('PLAYER', 'TEAM', name='card_type', native_enum=False, length=32), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.create_index('ix_user_cards_owner_template', ['user_id', 'card_type', 'card_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cards_user_id'), ['user_id'], unique=False)

    op.create_table('player_card_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarity', native_enum=False, length=32), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'rarity', name='uq_player_rarity')
    )
    with op.batch_alter_table('player_card_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_card_templates_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_card_templates_rarity'), ['rarity'], unique=False)

    op.create_table('player_match_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_stat_match_player')
    )
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_stats_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_player_id'), ['player_id'], unique=False)

    op.create_table('points_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('is_perfect_xi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_points_user_match')
    )
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_history_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_history_user_id'), ['user_id'], unique=False)

    op.create_table('squad_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('user_card_id', sa.String(length=36), nullable=False),
    sa.Column('position_slot', sa.Enum('GK', 'F1', 'F2', 'F3', 'F4', 'SUB1', 'SUB2', name='position_slot', native_enum=False, length=32), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice_captain', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', 'player_id', name='uq_squad_player'),
    sa.UniqueConstraint('user_id', 'match_id', 'position_slot', name='uq_squad_slot')
    )
    with op.batch_alter_table('squad_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squad_entries_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squad_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_squad_entries_match_id'))

    op.drop_table('squad_entries')
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_history_match_id'))

    op.drop_table('points_history')
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_match_id'))

    op.drop_table('player_match_stats')
    with op.batch_alter_table('player_card_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_card_templates_rarity'))
        batch_op.drop_index(batch_op.f('ix_player_card_templates_player_id'))

    op.drop_table('player_card_templates')
    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_cards_user_id'))
        batch_op.drop_index('ix_user_cards_owner_template')

    op.drop_table('user_cards')
    with op.batch_alter_table('trade_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_offers_status'))
        batch_op.drop_index(batch_op.f('ix_trade_offers_sender_id'))
        batch_op.drop_index(batch_op.f('ix_trade_offers_receiver_id'))

    op.drop_table('trade_offers')
    with op.batch_alter_table('team_card_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_card_templates_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_card_templates_rarity'))

    op.drop_table('team_card_templates')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_slug'))
        batch_op.drop_index(batch_op.f('ix_players_external_id'))

    op.drop_table('players')
    with op.batch_alter_table('pack_openings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pack_openings_user_id'))

    op.drop_table('pack_openings')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_tournament_slug'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_start_time'))
        batch_op.drop_index(batch_op.f('ix_matches_slug'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_external_id'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team_id'))

    op.drop_table('matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_external_id'))

    op.drop_table('teams')
    op.drop_table('sync_state')
    op.drop_table('packs')
    # ### end Alembic commands ###
